### ISSUE TITLE
Sygons name over the left side icon

### ISSUE THREAD

**Issue by ghost** [synergycrowds/scpi#10]
Sentiment indicator - right side - on Sygons - the list of names go over the left side icon if the name is longer.

**device:** Macbook Pro 13" - 13,3-inch (2560 x 1600)
**OS:** macOS Catalina
**browser:** Firefox

**Comment by mocamircea** [comment]
check and manage @rechinu007

**Comment by ghost** [comment]
Look like the problem is somehow resolved. The name is not over the left icon anymore but the shorter names are not too far from the icon? I'll put an image in slack.

**Comment by mocamircea** [comment]
👍👍

**Comment by mocamircea** [comment]
opened #15 for new design of the right panel @rechinu007
