### ISSUE TITLE
View on Github button - redirecting to a non-existing page

### ISSUE THREAD

**Issue by ghost** [synergycrowds/scpi#2]
1. After login click on Help -> Documention.
2. https://synergycrowds.github.io/ will be opened in a new tab. 
3. Click on **View on GIthub** button from header
4. 404 returned

**Comment by mocamircea** [comment]
The "View on Github" button is generated by Github in the header of the SynergyCrowds Github doc page.
HTTP 404 is returned only when user is not logged in to Github.
