### ISSUE TITLE
Portfolio Builder - does not identify user portfolio content

### ISSUE THREAD

**Issue by mocamircea** [synergycrowds/scpi#7]
After re-login the content identified for the logged account is not correct.

**Comment by mocamircea** [comment]
@rechinu007

**Comment by ghost** [comment]
On my side even after I close the portfolio window and re-enter again on it, the saved data is not there anymore.

**Comment by mocamircea** [comment]
fixed, available in next update

**Comment by mocamircea** [comment]
Oct 22
